(function () {
    'use strict';

    angular.module('app')
        .service('IconService', IconService);

    function IconService() {
        var data = [
            {
                "category": "Action Icons",
                "icons": [
                    { "category": "action", "name": "add_contact" },
                    { "category": "action", "name": "announcement" },
                    { "category": "action", "name": "apex" },
                    { "category": "action", "name": "approval" },
                    { "category": "action", "name": "back" },
                    { "category": "action", "name": "call" },
                    { "category": "action", "name": "canvas" },
                    { "category": "action", "name": "change_owner" },
                    { "category": "action", "name": "change_record_type" },
                    { "category": "action", "name": "check" },
                    { "category": "action", "name": "clone" },
                    { "category": "action", "name": "close" },
                    { "category": "action", "name": "defer" },
                    { "category": "action", "name": "delete" },
                    { "category": "action", "name": "description" },
                    { "category": "action", "name": "dial_in" },
                    { "category": "action", "name": "download" },
                    { "category": "action", "name": "edit_groups" },
                    { "category": "action", "name": "edit_relationship" },
                    { "category": "action", "name": "edit" },
                    { "category": "action", "name": "email" },
                    { "category": "action", "name": "fallback" },
                    { "category": "action", "name": "filter" },
                    { "category": "action", "name": "flow" },
                    { "category": "action", "name": "follow" },
                    { "category": "action", "name": "following" },
                    { "category": "action", "name": "freeze_user" },
                    { "category": "action", "name": "goal" },
                    { "category": "action", "name": "google_news" },
                    { "category": "action", "name": "join_group" },
                    { "category": "action", "name": "lead_convert" },
                    { "category": "action", "name": "leave_group" },
                    { "category": "action", "name": "log_a_call" },
                    { "category": "action", "name": "log_event" },
                    { "category": "action", "name": "manage_perm_sets" },
                    { "category": "action", "name": "map" },
                    { "category": "action", "name": "more" },
                    { "category": "action", "name": "new_account" },
                    { "category": "action", "name": "new_campaign" },
                    { "category": "action", "name": "new_case" },
                    { "category": "action", "name": "new_child_case" },
                    { "category": "action", "name": "new_contact" },
                    { "category": "action", "name": "new_custom1" },
                    { "category": "action", "name": "new_custom2" },
                    { "category": "action", "name": "new_custom3" },
                    { "category": "action", "name": "new_custom4" },
                    { "category": "action", "name": "new_custom5" },
                    { "category": "action", "name": "new_custom6" },
                    { "category": "action", "name": "new_custom7" },
                    { "category": "action", "name": "new_custom8" },
                    { "category": "action", "name": "new_custom9" },
                    { "category": "action", "name": "new_custom10" },
                    { "category": "action", "name": "new_custom11" },
                    { "category": "action", "name": "new_custom12" },
                    { "category": "action", "name": "new_custom13" },
                    { "category": "action", "name": "new_custom14" },
                    { "category": "action", "name": "new_custom15" },
                    { "category": "action", "name": "new_custom16" },
                    { "category": "action", "name": "new_custom17" },
                    { "category": "action", "name": "new_custom18" },
                    { "category": "action", "name": "new_custom19" },
                    { "category": "action", "name": "new_custom20" },
                    { "category": "action", "name": "new_custom21" },
                    { "category": "action", "name": "new_custom22" },
                    { "category": "action", "name": "new_custom23" },
                    { "category": "action", "name": "new_custom24" },
                    { "category": "action", "name": "new_custom25" },
                    { "category": "action", "name": "new_custom26" },
                    { "category": "action", "name": "new_custom27" },
                    { "category": "action", "name": "new_custom28" },
                    { "category": "action", "name": "new_custom29" },
                    { "category": "action", "name": "new_custom30" },
                    { "category": "action", "name": "new_custom31" },
                    { "category": "action", "name": "new_custom32" },
                    { "category": "action", "name": "new_custom33" },
                    { "category": "action", "name": "new_custom34" },
                    { "category": "action", "name": "new_custom35" },
                    { "category": "action", "name": "new_custom36" },
                    { "category": "action", "name": "new_custom37" },
                    { "category": "action", "name": "new_custom38" },
                    { "category": "action", "name": "new_custom39" },
                    { "category": "action", "name": "new_custom40" },
                    { "category": "action", "name": "new_custom41" },
                    { "category": "action", "name": "new_custom42" },
                    { "category": "action", "name": "new_custom43" },
                    { "category": "action", "name": "new_custom44" },
                    { "category": "action", "name": "new_custom45" },
                    { "category": "action", "name": "new_custom46" },
                    { "category": "action", "name": "new_custom47" },
                    { "category": "action", "name": "new_custom48" },
                    { "category": "action", "name": "new_custom49" },
                    { "category": "action", "name": "new_custom50" },
                    { "category": "action", "name": "new_custom51" },
                    { "category": "action", "name": "new_custom52" },
                    { "category": "action", "name": "new_custom53" },
                    { "category": "action", "name": "new_custom54" },
                    { "category": "action", "name": "new_custom55" },
                    { "category": "action", "name": "new_custom56" },
                    { "category": "action", "name": "new_custom57" },
                    { "category": "action", "name": "new_custom58" },
                    { "category": "action", "name": "new_custom59" },
                    { "category": "action", "name": "new_custom60" },
                    { "category": "action", "name": "new_custom61" },
                    { "category": "action", "name": "new_custom62" },
                    { "category": "action", "name": "new_custom63" },
                    { "category": "action", "name": "new_custom64" },
                    { "category": "action", "name": "new_custom65" },
                    { "category": "action", "name": "new_custom66" },
                    { "category": "action", "name": "new_custom67" },
                    { "category": "action", "name": "new_custom68" },
                    { "category": "action", "name": "new_custom69" },
                    { "category": "action", "name": "new_custom70" },
                    { "category": "action", "name": "new_custom71" },
                    { "category": "action", "name": "new_custom72" },
                    { "category": "action", "name": "new_custom73" },
                    { "category": "action", "name": "new_custom74" },
                    { "category": "action", "name": "new_custom75" },
                    { "category": "action", "name": "new_custom76" },
                    { "category": "action", "name": "new_custom77" },
                    { "category": "action", "name": "new_custom78" },
                    { "category": "action", "name": "new_custom79" },
                    { "category": "action", "name": "new_custom80" },
                    { "category": "action", "name": "new_custom81" },
                    { "category": "action", "name": "new_custom82" },
                    { "category": "action", "name": "new_custom83" },
                    { "category": "action", "name": "new_custom84" },
                    { "category": "action", "name": "new_custom85" },
                    { "category": "action", "name": "new_custom86" },
                    { "category": "action", "name": "new_custom87" },
                    { "category": "action", "name": "new_custom88" },
                    { "category": "action", "name": "new_custom89" },
                    { "category": "action", "name": "new_custom90" },
                    { "category": "action", "name": "new_custom91" },
                    { "category": "action", "name": "new_custom92" },
                    { "category": "action", "name": "new_custom93" },
                    { "category": "action", "name": "new_custom94" },
                    { "category": "action", "name": "new_custom95" },
                    { "category": "action", "name": "new_custom96" },
                    { "category": "action", "name": "new_custom97" },
                    { "category": "action", "name": "new_custom98" },
                    { "category": "action", "name": "new_custom99" },
                    { "category": "action", "name": "new_custom100" },
                    { "category": "action", "name": "new_event" },
                    { "category": "action", "name": "new_group" },
                    { "category": "action", "name": "new_lead" },
                    { "category": "action", "name": "new_note" },
                    { "category": "action", "name": "new_notebook" },
                    { "category": "action", "name": "new_opportunity" },
                    { "category": "action", "name": "new_task" },
                    { "category": "action", "name": "new" },
                    { "category": "action", "name": "password_unlock" },
                    { "category": "action", "name": "preview" },
                    { "category": "action", "name": "priority" },
                    { "category": "action", "name": "question_post_action" },
                    { "category": "action", "name": "quote" },
                    { "category": "action", "name": "record" },
                    { "category": "action", "name": "refresh" },
                    { "category": "action", "name": "reject" },
                    { "category": "action", "name": "remove" },
                    { "category": "action", "name": "reset_password" },
                    { "category": "action", "name": "share_file" },
                    { "category": "action", "name": "share_link" },
                    { "category": "action", "name": "share_poll" },
                    { "category": "action", "name": "share_post" },
                    { "category": "action", "name": "share_thanks" },
                    { "category": "action", "name": "sort" },
                    { "category": "action", "name": "submit_for_approval" },
                    { "category": "action", "name": "update_status" },
                    { "category": "action", "name": "update" },
                    { "category": "action", "name": "user_activation" },
                    { "category": "action", "name": "web_link" }
                ]
            },
            {
               "category": "Doctype Icons",
               "icons": [
                    { "category": "doctype", "name": "ai", "paths": 4 },
                    { "category": "doctype", "name": "attachment", "paths": 4 },
                    { "category": "doctype", "name": "audio", "paths": 4 },
                    { "category": "doctype", "name": "csv", "paths": 4 },
                    { "category": "doctype", "name": "eps", "paths": 4 },
                    { "category": "doctype", "name": "excel", "paths": 4 },
                    { "category": "doctype", "name": "exe", "paths": 4 },
                    { "category": "doctype", "name": "flash", "paths": 4 },
                    { "category": "doctype", "name": "gdoc", "paths": 4 },
                    { "category": "doctype", "name": "gdocs", "paths": 4 },
                    { "category": "doctype", "name": "gpres", "paths": 4 },
                    { "category": "doctype", "name": "gsheet", "paths": 4 },
                    { "category": "doctype", "name": "html", "paths": 4 },
                    { "category": "doctype", "name": "image", "paths": 4 },
                    { "category": "doctype", "name": "keynote", "paths": 4 },
                    { "category": "doctype", "name": "link", "paths": 4 },
                    { "category": "doctype", "name": "mp4", "paths": 4 },
                    { "category": "doctype", "name": "overlay", "paths": 5 },
                    { "category": "doctype", "name": "pack", "paths": 4 },
                    { "category": "doctype", "name": "pages", "paths": 4 },
                    { "category": "doctype", "name": "pdf", "paths": 4 },
                    { "category": "doctype", "name": "ppt", "paths": 4 },
                    { "category": "doctype", "name": "psd", "paths": 4 },
                    { "category": "doctype", "name": "rtf", "paths": 4 },
                    { "category": "doctype", "name": "slide", "paths": 4 },
                    { "category": "doctype", "name": "stypi", "paths": 5 },
                    { "category": "doctype", "name": "txt", "paths": 4 },
                    { "category": "doctype", "name": "unknown", "paths": 3 },
                    { "category": "doctype", "name": "video", "paths": 4 },
                    { "category": "doctype", "name": "visio", "paths": 4 },
                    { "category": "doctype", "name": "webex", "paths": 5 },
                    { "category": "doctype", "name": "word", "paths": 4 },
                    { "category": "doctype", "name": "xml", "paths": 4 },
                    { "category": "doctype", "name": "zip", "paths": 4 }
               ]
            },
            {
                "category": "Custom Icons",
                "icons": [
                    { "category": "custom", "name": "custom1" },
                    { "category": "custom", "name": "custom2" },
                    { "category": "custom", "name": "custom3" },
                    { "category": "custom", "name": "custom4" },
                    { "category": "custom", "name": "custom5" },
                    { "category": "custom", "name": "custom6" },
                    { "category": "custom", "name": "custom7" },
                    { "category": "custom", "name": "custom8" },
                    { "category": "custom", "name": "custom9" },
                    { "category": "custom", "name": "custom10" },
                    { "category": "custom", "name": "custom11" },
                    { "category": "custom", "name": "custom12" },
                    { "category": "custom", "name": "custom13" },
                    { "category": "custom", "name": "custom14" },
                    { "category": "custom", "name": "custom15" },
                    { "category": "custom", "name": "custom16" },
                    { "category": "custom", "name": "custom17" },
                    { "category": "custom", "name": "custom18" },
                    { "category": "custom", "name": "custom19" },
                    { "category": "custom", "name": "custom20" },
                    { "category": "custom", "name": "custom21" },
                    { "category": "custom", "name": "custom22" },
                    { "category": "custom", "name": "custom23" },
                    { "category": "custom", "name": "custom24" },
                    { "category": "custom", "name": "custom25" },
                    { "category": "custom", "name": "custom26" },
                    { "category": "custom", "name": "custom27" },
                    { "category": "custom", "name": "custom28" },
                    { "category": "custom", "name": "custom29" },
                    { "category": "custom", "name": "custom30" },
                    { "category": "custom", "name": "custom31" },
                    { "category": "custom", "name": "custom32" },
                    { "category": "custom", "name": "custom33" },
                    { "category": "custom", "name": "custom34" },
                    { "category": "custom", "name": "custom35" },
                    { "category": "custom", "name": "custom36" },
                    { "category": "custom", "name": "custom37" },
                    { "category": "custom", "name": "custom38" },
                    { "category": "custom", "name": "custom39" },
                    { "category": "custom", "name": "custom40" },
                    { "category": "custom", "name": "custom41" },
                    { "category": "custom", "name": "custom42" },
                    { "category": "custom", "name": "custom43" },
                    { "category": "custom", "name": "custom44" },
                    { "category": "custom", "name": "custom45" },
                    { "category": "custom", "name": "custom46" },
                    { "category": "custom", "name": "custom47" },
                    { "category": "custom", "name": "custom48" },
                    { "category": "custom", "name": "custom49" },
                    { "category": "custom", "name": "custom50" },
                    { "category": "custom", "name": "custom51" },
                    { "category": "custom", "name": "custom52" },
                    { "category": "custom", "name": "custom53" },
                    { "category": "custom", "name": "custom54" },
                    { "category": "custom", "name": "custom55" },
                    { "category": "custom", "name": "custom56" },
                    { "category": "custom", "name": "custom57" },
                    { "category": "custom", "name": "custom58" },
                    { "category": "custom", "name": "custom59" },
                    { "category": "custom", "name": "custom60" },
                    { "category": "custom", "name": "custom61" },
                    { "category": "custom", "name": "custom62" },
                    { "category": "custom", "name": "custom63" },
                    { "category": "custom", "name": "custom64" },
                    { "category": "custom", "name": "custom65" },
                    { "category": "custom", "name": "custom66" },
                    { "category": "custom", "name": "custom67" },
                    { "category": "custom", "name": "custom68" },
                    { "category": "custom", "name": "custom69" },
                    { "category": "custom", "name": "custom70" },
                    { "category": "custom", "name": "custom71" },
                    { "category": "custom", "name": "custom72" },
                    { "category": "custom", "name": "custom73" },
                    { "category": "custom", "name": "custom74" },
                    { "category": "custom", "name": "custom75" },
                    { "category": "custom", "name": "custom76" },
                    { "category": "custom", "name": "custom77" },
                    { "category": "custom", "name": "custom78" },
                    { "category": "custom", "name": "custom79" },
                    { "category": "custom", "name": "custom80" },
                    { "category": "custom", "name": "custom81" },
                    { "category": "custom", "name": "custom82" },
                    { "category": "custom", "name": "custom83" },
                    { "category": "custom", "name": "custom84" },
                    { "category": "custom", "name": "custom85" },
                    { "category": "custom", "name": "custom86" },
                    { "category": "custom", "name": "custom87" },
                    { "category": "custom", "name": "custom88" },
                    { "category": "custom", "name": "custom89" },
                    { "category": "custom", "name": "custom90" },
                    { "category": "custom", "name": "custom91" },
                    { "category": "custom", "name": "custom92" },
                    { "category": "custom", "name": "custom93" },
                    { "category": "custom", "name": "custom94" },
                    { "category": "custom", "name": "custom95" },
                    { "category": "custom", "name": "custom96" },
                    { "category": "custom", "name": "custom97" },
                    { "category": "custom", "name": "custom98" },
                    { "category": "custom", "name": "custom99" },
                    { "category": "custom", "name": "custom100" }
                ]
            },
            {
                "category": "Standard Icons",
                "icons": [
                    { "category": "standard", "name": "account" },
                    { "category": "standard", "name": "announcement" },
                    { "category": "standard", "name": "answer_best" },
                    { "category": "standard", "name": "answer_private" },
                    { "category": "standard", "name": "answer_public" },
                    { "category": "standard", "name": "approval" },
                    { "category": "standard", "name": "apps_admin" },
                    { "category": "standard", "name": "apps" },
                    { "category": "standard", "name": "article" },
                    { "category": "standard", "name": "avatar_loading" },
                    { "category": "standard", "name": "avatar" },
                    { "category": "standard", "name": "calibration" },
                    { "category": "standard", "name": "call_history" },
                    { "category": "standard", "name": "call" },
                    { "category": "standard", "name": "campaign_members" },
                    { "category": "standard", "name": "campaign" },
                    { "category": "standard", "name": "canvas" },
                    { "category": "standard", "name": "case_change_status" },
                    { "category": "standard", "name": "case_comment" },
                    { "category": "standard", "name": "case_email" },
                    { "category": "standard", "name": "case_log_a_call" },
                    { "category": "standard", "name": "case_transcript" },
                    { "category": "standard", "name": "case" },
                    { "category": "standard", "name": "client" },
                    { "category": "standard", "name": "coaching" },
                    { "category": "standard", "name": "connected_apps" },
                    { "category": "standard", "name": "contact" },
                    { "category": "standard", "name": "contract" },
                    { "category": "standard", "name": "custom" },
                    { "category": "standard", "name": "dashboard" },
                    { "category": "standard", "name": "default" },
                    { "category": "standard", "name": "document" },
                    { "category": "standard", "name": "drafts" },
                    { "category": "standard", "name": "email_chatter" },
                    { "category": "standard", "name": "email" },
                    { "category": "standard", "name": "empty" },
                    { "category": "standard", "name": "endorsement" },
                    { "category": "standard", "name": "environment_hub" },
                    { "category": "standard", "name": "event" },
                    { "category": "standard", "name": "feed" },
                    { "category": "standard", "name": "feedback" },
                    { "category": "standard", "name": "file" },
                    { "category": "standard", "name": "flow" },
                    { "category": "standard", "name": "generic_loading" },
                    { "category": "standard", "name": "goals" },
                    { "category": "standard", "name": "group_loading" },
                    { "category": "standard", "name": "groups" },
                    { "category": "standard", "name": "home" },
                    { "category": "standard", "name": "household" },
                    { "category": "standard", "name": "insights" },
                    { "category": "standard", "name": "investment_account" },
                    { "category": "standard", "name": "lead" },
                    { "category": "standard", "name": "link" },
                    { "category": "standard", "name": "log_a_call" },
                    { "category": "standard", "name": "marketing_actions" },
                    { "category": "standard", "name": "marketing_resources" },
                    { "category": "standard", "name": "metrics" },
                    { "category": "standard", "name": "news" },
                    { "category": "standard", "name": "note" },
                    { "category": "standard", "name": "opportunity" },
                    { "category": "standard", "name": "orders" },
                    { "category": "standard", "name": "people" },
                    { "category": "standard", "name": "performance" },
                    { "category": "standard", "name": "photo" },
                    { "category": "standard", "name": "poll" },
                    { "category": "standard", "name": "portal" },
                    { "category": "standard", "name": "post" },
                    { "category": "standard", "name": "pricebook" },
                    { "category": "standard", "name": "process" },
                    { "category": "standard", "name": "product" },
                    { "category": "standard", "name": "question_best" },
                    { "category": "standard", "name": "question_feed" },
                    { "category": "standard", "name": "quotes" },
                    { "category": "standard", "name": "recent" },
                    { "category": "standard", "name": "record" },
                    { "category": "standard", "name": "related_list" },
                    { "category": "standard", "name": "report" },
                    { "category": "standard", "name": "reward" },
                    { "category": "standard", "name": "scan_card" },
                    { "category": "standard", "name": "skill_entity" },
                    { "category": "standard", "name": "social" },
                    { "category": "standard", "name": "solution" },
                    { "category": "standard", "name": "sossession" },
                    { "category": "standard", "name": "task" },
                    { "category": "standard", "name": "task2" },
                    { "category": "standard", "name": "team_member" },
                    { "category": "standard", "name": "thanks_loading" },
                    { "category": "standard", "name": "thanks" },
                    { "category": "standard", "name": "today" },
                    { "category": "standard", "name": "topic" },
                    { "category": "standard", "name": "unmatched" },
                    { "category": "standard", "name": "user" }
                ]
            },
            {
                "category": "Utility Icons",
                "icons": [
                    { "category": "utility", "name": "add" },
                    { "category": "utility", "name": "adduser" },
                    { "category": "utility", "name": "announcement" },
                    { "category": "utility", "name": "apps" },
                    { "category": "utility", "name": "arrowdown" },
                    { "category": "utility", "name": "arrowup" },
                    { "category": "utility", "name": "attach" },
                    { "category": "utility", "name": "back" },
                    { "category": "utility", "name": "ban" },
                    { "category": "utility", "name": "bold" },
                    { "category": "utility", "name": "bookmark" },
                    { "category": "utility", "name": "brush" },
                    { "category": "utility", "name": "bucket" },
                    { "category": "utility", "name": "builder" },
                    { "category": "utility", "name": "call" },
                    { "category": "utility", "name": "capslock" },
                    { "category": "utility", "name": "cases" },
                    { "category": "utility", "name": "center_align_text" },
                    { "category": "utility", "name": "chart" },
                    { "category": "utility", "name": "chat" },
                    { "category": "utility", "name": "check" },
                    { "category": "utility", "name": "checkin" },
                    { "category": "utility", "name": "chevrondown" },
                    { "category": "utility", "name": "chevronleft" },
                    { "category": "utility", "name": "chevronright" },
                    { "category": "utility", "name": "chevronup" },
                    { "category": "utility", "name": "clear" },
                    { "category": "utility", "name": "clock" },
                    { "category": "utility", "name": "close" },
                    { "category": "utility", "name": "comments" },
                    { "category": "utility", "name": "company" },
                    { "category": "utility", "name": "connected_apps" },
                    { "category": "utility", "name": "contract_alt" },
                    { "category": "utility", "name": "contract" },
                    { "category": "utility", "name": "copy" },
                    { "category": "utility", "name": "crossfilter" },
                    { "category": "utility", "name": "custom_apps" },
                    { "category": "utility", "name": "cut" },
                    { "category": "utility", "name": "dash" },
                    { "category": "utility", "name": "dayview" },
                    { "category": "utility", "name": "delete" },
                    { "category": "utility", "name": "deprecate" },
                    { "category": "utility", "name": "desktop" },
                    { "category": "utility", "name": "down" },
                    { "category": "utility", "name": "download" },
                    { "category": "utility", "name": "edit" },
                    { "category": "utility", "name": "email" },
                    { "category": "utility", "name": "end_call" },
                    { "category": "utility", "name": "erect_window" },
                    { "category": "utility", "name": "error" },
                    { "category": "utility", "name": "event" },
                    { "category": "utility", "name": "expand_alt" },
                    { "category": "utility", "name": "expand" },
                    { "category": "utility", "name": "favorite" },
                    { "category": "utility", "name": "filter" },
                    { "category": "utility", "name": "filterList" },
                    { "category": "utility", "name": "forward" },
                    { "category": "utility", "name": "frozen" },
                    { "category": "utility", "name": "groups" },
                    { "category": "utility", "name": "help" },
                    { "category": "utility", "name": "home" },
                    { "category": "utility", "name": "identity" },
                    { "category": "utility", "name": "image" },
                    { "category": "utility", "name": "inbox" },
                    { "category": "utility", "name": "info" },
                    { "category": "utility", "name": "insert_tag_field" },
                    { "category": "utility", "name": "insert_template" },
                    { "category": "utility", "name": "italic" },
                    { "category": "utility", "name": "justify_text" },
                    { "category": "utility", "name": "kanban" },
                    { "category": "utility", "name": "knowledge_base" },
                    { "category": "utility", "name": "layout" },
                    { "category": "utility", "name": "left_align_text" },
                    { "category": "utility", "name": "left" },
                    { "category": "utility", "name": "like" },
                    { "category": "utility", "name": "link" },
                    { "category": "utility", "name": "list" },
                    { "category": "utility", "name": "location" },
                    { "category": "utility", "name": "lock" },
                    { "category": "utility", "name": "logout" },
                    { "category": "utility", "name": "magicwand" },
                    { "category": "utility", "name": "matrix" },
                    { "category": "utility", "name": "minimize_window" },
                    { "category": "utility", "name": "monthlyview" },
                    { "category": "utility", "name": "move" },
                    { "category": "utility", "name": "muted" },
                    { "category": "utility", "name": "new_window" },
                    { "category": "utility", "name": "new" },
                    { "category": "utility", "name": "news" },
                    { "category": "utility", "name": "notebook" },
                    { "category": "utility", "name": "notification" },
                    { "category": "utility", "name": "office365" },
                    { "category": "utility", "name": "offline" },
                    { "category": "utility", "name": "open_folder" },
                    { "category": "utility", "name": "open" },
                    { "category": "utility", "name": "opened_folder" },
                    { "category": "utility", "name": "package_org_beta" },
                    { "category": "utility", "name": "package_org" },
                    { "category": "utility", "name": "package" },
                    { "category": "utility", "name": "page" },
                    { "category": "utility", "name": "palette" },
                    { "category": "utility", "name": "paste" },
                    { "category": "utility", "name": "people" },
                    { "category": "utility", "name": "phone_landscape" },
                    { "category": "utility", "name": "phone_portrait" },
                    { "category": "utility", "name": "photo" },
                    { "category": "utility", "name": "power" },
                    { "category": "utility", "name": "preview" },
                    { "category": "utility", "name": "priority" },
                    { "category": "utility", "name": "process" },
                    { "category": "utility", "name": "push" },
                    { "category": "utility", "name": "puzzle" },
                    { "category": "utility", "name": "question" },
                    { "category": "utility", "name": "questions_and_answers" },
                    { "category": "utility", "name": "record" },
                    { "category": "utility", "name": "redo" },
                    { "category": "utility", "name": "refresh" },
                    { "category": "utility", "name": "relate" },
                    { "category": "utility", "name": "remove_formatting" },
                    { "category": "utility", "name": "remove_link" },
                    { "category": "utility", "name": "replace" },
                    { "category": "utility", "name": "reply" },
                    { "category": "utility", "name": "reset_password" },
                    { "category": "utility", "name": "retweet" },
                    { "category": "utility", "name": "richtextbulletedlist" },
                    { "category": "utility", "name": "richtextindent" },
                    { "category": "utility", "name": "richtextnumberedlist" },
                    { "category": "utility", "name": "richtextoutdent" },
                    { "category": "utility", "name": "right_align_text" },
                    { "category": "utility", "name": "right" },
                    { "category": "utility", "name": "rotate" },
                    { "category": "utility", "name": "rows" },
                    { "category": "utility", "name": "salesforce1" },
                    { "category": "utility", "name": "search" },
                    { "category": "utility", "name": "settings" },
                    { "category": "utility", "name": "setup_assistant_guide" },
                    { "category": "utility", "name": "setup" },
                    { "category": "utility", "name": "share" },
                    { "category": "utility", "name": "shield" },
                    { "category": "utility", "name": "side_list" },
                    { "category": "utility", "name": "signpost" },
                    { "category": "utility", "name": "sms" },
                    { "category": "utility", "name": "snippet" },
                    { "category": "utility", "name": "socialshare" },
                    { "category": "utility", "name": "sort" },
                    { "category": "utility", "name": "spinner" },
                    { "category": "utility", "name": "standard_objects" },
                    { "category": "utility", "name": "stop" },
                    { "category": "utility", "name": "strikethrough" },
                    { "category": "utility", "name": "success" },
                    { "category": "utility", "name": "summary" },
                    { "category": "utility", "name": "summarydetail" },
                    { "category": "utility", "name": "switch" },
                    { "category": "utility", "name": "table" },
                    { "category": "utility", "name": "tablet_landscape" },
                    { "category": "utility", "name": "tablet_portrait" },
                    { "category": "utility", "name": "text_background_color" },
                    { "category": "utility", "name": "text_color" },
                    { "category": "utility", "name": "threedots" },
                    { "category": "utility", "name": "tile_card_list" },
                    { "category": "utility", "name": "topic" },
                    { "category": "utility", "name": "trail" },
                    { "category": "utility", "name": "undelete" },
                    { "category": "utility", "name": "undeprecate" },
                    { "category": "utility", "name": "underline" },
                    { "category": "utility", "name": "undo" },
                    { "category": "utility", "name": "unlock" },
                    { "category": "utility", "name": "unmuted" },
                    { "category": "utility", "name": "up" },
                    { "category": "utility", "name": "upload" },
                    { "category": "utility", "name": "user" },
                    { "category": "utility", "name": "volume_high" },
                    { "category": "utility", "name": "volume_low" },
                    { "category": "utility", "name": "volume_off" },
                    { "category": "utility", "name": "warning" },
                    { "category": "utility", "name": "weeklyview" },
                    { "category": "utility", "name": "world" },
                    { "category": "utility", "name": "zoomin" },
                    { "category": "utility", "name": "zoomout" }
                ]
            }
        ];

        return data;
    }
}());